### ISSUE TITLE
May I ask how to solve this problem? Thank you

### ISSUE THREAD

**Issue by Leon-dai** [ZelongZeng/PLCD#3]
May I ask why this error is reported when I follow the steps to execute Train&Evaluation for the Ground Dragon presentation to the last step of Evaluation for ground to drone retrieval: in `Python evaluate_h5. py -- name $Name_of Step-3 $`?
```
Torch. Size ([2579, 512])
Torch. Size ([17119, 512])
Traceback (most recent call last):
File "/mnt/home/daixh/Experiment/PLCD/evaluate_h5. py", line 107, in <module>
CMC = CMC + CMC_tmp
RuntimeError: The size of tensor a (51355) must match the size of tensor b (17119) at non singleton dimension 0
```
The command steps I executed are as follows:
`python train_PL_G2D.py --train_all --batchsize 8 --pool max --data_dir /home/daixh/mydata/Experiment/PLCD/dataset/University/University-Release/train --gen 0 --seed 0 --name step1 --gpu_ids 3 --lambda1 1.0 --lambda2 0.1 --easy_pos`

`python train_PL_G2D.py --train_all --batchsize 8 --pool max --data_dir /home/daixh/mydata/Experiment/PLCD/dataset/University/University-Release/train --gen 1 --seed 0 --old_name step1 --name step2 --gpu 3 --lambda1 1.0 --lambda2 0.1 --lambda3 1.0 --tau 0.1 --easy_pos`

`python train_PL_G2D.py --train_all --batchsize 8 --pool max --data_dir /home/daixh/mydata/Experiment/PLCD/dataset/University/University-Release/train --gen 2 --seed 0 --old_name step2 --name step3 --gpu 3 --lambda1 1.0 --lambda2 0.1 --lambda3 3.0 --tau 0.1 --hiera 13 --easy_pos`

`python test_PL_G2D.py --batchsize 8 --test_dir /home/daixh/mydata/Experiment/PLCD/dataset/University/University-Release/test --name step3 --gpu_ids 3 --low_altitude`

`python evaluate_h5.py --name step3`
Prior to this, the drone view library set has also been divided into three parts based on the captured altitude. The directory of my data is as follows：
![image](https://github.com/ZelongZeng/PLCD/assets/73450545/9a0d6855-89e5-49e8-8911-935bc371bbbd)
I found that 51355 is the number of images in the gallery_drone folder, and 17119 is the number of images in the gallery_drone_low folder
After calculation,There are a total of 51355 JPEG images in the directory/home/daixh/mydata/Experiment/PLCD/dataset/University/University Release/test/gallery_drone.
There are a total of 17119 JPEG images in the directory/home/daixh/mydata/Experiment/PLCD/dataset/University/University Release/test/gallery_drone_low.
May I ask if it is due to the addition of --low-altitude in this step of `python test_PL_G2D.py --batchsize 8 --test_dir /home/daixh/mydata/Experiment/PLCD/dataset/University/University-Release/test --name step3 --gpu_ids 3 --low_altitude`，Thank you

**Comment by Leon-dai** [comment]
I added a line of code in line 309 of test_PL_G2D. py to solve this problem
```
if opt.low_altitude:
    gallery_name = 'gallery_drone_low'
```

**Comment by ZelongZeng** [comment]
Hi Leon, 
Sorry for my late reply. 
Thank you for raising the related bug, and I am very pleased to hear that you have resolved this issue. I will do the modifications to the relevant parts. 
If you meet any problems in the feature, please feel free to send a message on GitHub at any time. 

Best regard.
